### A Pluto.jl notebook ###
# v0.14.7

using Markdown
using InteractiveUtils

# This Pluto notebook uses @bind for interactivity. When running this notebook outside of Pluto, the following 'mock version' of @bind gives bound variables a default value (instead of an error).
macro bind(def, element)
    quote
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : missing
        el
    end
end

# ╔═╡ 56c992d7-5f55-4f21-be9b-673db0c3565d
begin
	using PlutoUI
	using Plots, PlotThemes, LaTeXStrings
	using SymPy
	using Dates
end

# ╔═╡ 36385992-7458-4252-902d-89153ad3e85e
html"""
<style>
.div-50 {
  position: relative;
  height: 50px;
}
.div-100 {
  position: relative;
  height: 100px;
}
.div-200 {
  position: relative;
  height: 200px;
}
.div-300 {
  position: relative;
  height: 300px;
}
.div-400 {
  position: relative;
  height: 400px;
}

.right-formula {
  width: 50%;
  text-align: center;
  position: absolute;
  top: 0;
  right: 0;
  padding: 5px;
  border: 2px solid blue;
}

</style>

"""

# ╔═╡ 7532bb48-d0a5-11eb-0369-23288ac68dbc
TableOfContents(title="MATH102")

# ╔═╡ d1815ea6-9a32-4d88-b580-95f29d7ef914
begin
	struct PlotData
		x::StepRangeLen
		fun::Function
		lb::Union{Integer,Vector{Float64}}
	end
	PlotData(x,f)=PlotData(x,f,0)	
	@recipe function f(t::PlotData; customcolor = :green, fillit=true)
		x, fun, lb = t.x, t.fun, t.lb
		xrotation --> 45
		zrotation --> 6, :quiet
		aspect_ratio --> 1
		framestyle --> :origin
		label-->nothing
		fill --> (fillit ? (lb,0.5,customcolor) : nothing)
		x, fun.(x)
	end
	x, y = symbols("x,y", real=true)
	
	html""
end

# ╔═╡ d7831013-a8bf-4bed-83f3-c436b2dd1464
md"""
# Chapter 7: Techniques of Integration

## Section 7.1
**Integration by Parts**

*The integration rule that corresponds to the Product Rule for differentiation is called __integration by parts__*
"""

# ╔═╡ 561cdfe6-fde5-4e09-bbac-8c9f9b68917c
md"""
### Indefinite Integrals
```math
\int f(x)g'\,(x) dx = f(x) g(x) - \int g(x) f'\,(x) dx
```
"""

# ╔═╡ 17b3c7a5-3170-4b6b-81b5-fc5f29eedd0f
md"""
**Example**

```math 
\int x \cos(x) dx 
```


"""

# ╔═╡ ea89d5dc-3d70-42d3-9cc7-6cc4c3e8ad2b
begin
	
	md"""
	**Solution:**
	
	```math
	\int x \cos(x) dx = \int \underbrace{x}_{f(x)} \overbrace{\cos(x)}^{g'(x)} dx = x \sin(x) - \int \sin(x) \overbrace{ \;\;\;\;dx}^{f'\,(x) dx} = x\sin(x) + \cos(x) +C  
	
	```
	"""
end

# ╔═╡ 1c821257-3b61-4187-a556-0e5736af27b2
md"""
**Remarks:**

```math
\int f(x)g'\,(x) dx = f(x) g(x) - \int g(x) f'\,(x) dx 
```
  
```math
\begin{array}{lll}
  u=f(x), & \qquad & dv=g'(x) dx \\
      &\searrow&\\
  du = f'(x)dx & \underset{-}{\longleftarrow} & v = g(x) 
  \end{array}
```


  
```math
\int u dv = uv - \int v du 
```
**_It is helpful to use the pattern:_**
```math
\begin{array}{rcr}
  u=\fbox{\rule{0.2in}{0pt}\rule[-0.1ex]{0pt}{2ex}} & \qquad & dv=\fbox{\rule{0.2in}{0pt}\rule[-0.1ex]{0pt}{2ex}} \\
      &\searrow&\\
  du = \fbox{\rule{0.2in}{0pt}\rule[-0.1ex]{0pt}{2ex}}& \underset{-}{\longleftarrow} & v = \fbox{\rule{0.2in}{0pt}\rule[-0.1ex]{0pt}{2ex}} 
  \end{array}
```

### Definite Integrals

```math
\int_a^b u dv = \left[uv\right]_a^b - \int_a^b v du
```
"""

# ╔═╡ 1a6fc415-eb31-4df1-a314-40aff9e0fa96
md"""
### Examples
__SOLUTION IN CLASS__

1. ``\int \ln x dx``
2. ``\int t^2 e^t dt ``
3. ``\int e^x \sin(x)dx``
4. ``\int_0^1 \tan^{-1}x dx``
5. ``\int x^3 \sin{\left(x\over 6\right)} dx``
6. ``\int \sin^5(x) dx``

"""

# ╔═╡ 030a2871-1b68-48c6-9f51-d4bcd0e86bb6
md"""
**Example**

Calculate the volume generated by rotating the region bounded by the curves ``y=\ln x``, ``y=0``, and ``x=2`` about each axis.
"""

# ╔═╡ 84ad187d-e4a7-48c6-8a5c-e9e518788689
begin

	release71 = Date(2021,6,25) < now()
	solution71 = release71 ? md"[Solution](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps7.1/ps7.1-solution.pdf)" : md"Solution will be released soon"
	md"""
	### [Problem Set 7.1](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps7.1/ps7.1.pdf)
	$(solution71)
	"""
end

# ╔═╡ 58719d77-9812-4002-b83f-2be9050ccf8a
md"""
## Section 7.2
**Trigonometric Integrals**

**RECALL**

```math



\displaystyle
\sin^2 x + \cos^2 x =1, \quad  \tan^2 x + 1 =\sec^2 x,  \quad  1+\cot^2 x  =\csc^2 x,

```

```math
\displaystyle
\cos^2 x = \frac{1 +\cos 2x }{2}, \quad \sin^2 x = \frac{1 -\cos 2x }{2}
```

```math
\displaystyle
\begin{array}{ccc}
\sin A\cos B & = & \frac{1}{2}\left[\sin(A-B)+\sin(A+B)\right], \\[0.2cm]
\sin A\sin B & = & \frac{1}{2}\left[\cos(A-B)-\cos(A+B)\right], \\[0.2cm]
\cos A\cos B & = & \frac{1}{2}\left[\cos(A-B)+\cos(A+B)\right], \\
\end{array}
```

```math
\int \tan x dx = \ln|\sec x| +C, \quad \int \sec x dx = \ln|\sec x+\tan x| +C
```


```math
\int \cot x dx = -\ln|\csc x| +C, \quad \int \csc x dx = \ln|\csc x-\cot x| +C
```
"""

# ╔═╡ 5bbb85cb-a5be-4010-bd41-caa339ef92dd
md"""
### Integrals of Powers of Sine and Cosine
```math
\int \sin^mx \cos^n x dx
```

* ``m`` is ``{\color{red}\text{odd}}``, write as ``\int \sin^{m-1}x \cos^n x \sin x  dx``. _Example_: $\int \sin^5x \cos^2 x dx$


* ``n`` is ``{\color{red}\text{odd}}``,  write as ``\int \sin^mx \cos^{n-1}\cos x  dx``. _Example_ ``\int \sin^5x \cos^3 x dx``


* ``m`` and ``n`` are ``{\color{red}\text{even}}``, use formulae (_Example_ ``\int \cos^2 x dx`` and  ``\int \sin^4 x dx``)
```math
\sin^2(x)=\frac{1-\cos(2x)}{2}, \quad \cos^2(x)=\frac{1+\cos(2x)}{2}.
```
"""

# ╔═╡ 9cc8c631-741d-4020-a74c-4fb4541fce70
md"""
### Integrals of Powers of Secant and Tangent

```math
\int \tan^mx \sec^n x dx
```

* ``n`` is even, write as ``\int \tan^mx \sec^{n-2}\sec^2 x  dx``. _Example_ ``\int \tan^6x \sec^4 x dx``


* ``m`` is odd, write as ``\int \tan^{m-1}x \sec^{n-1}\tan x\sec x  dx``. _Example_ ``\int \tan^5x \sec^7 x dx``.


"""

# ╔═╡ c67e0db7-f34a-4e4d-852b-23d3ab18be26
md"""
**Examples**

1. ``\int \tan^3 x dx``


2. ``\int \sec^3 x dx``

"""

# ╔═╡ 46b710e8-2903-47de-a26b-62537d8fd2e1
md"""
### Using Product Identities
```math 
\int \sin mx \cos n x dx, 
```
```math
\int \sin mx \sin n x dx, 
```
```math
\int \cos mx \cos n x dx.
```

Use


```math
\displaystyle
\begin{array}{ccc}
\sin A\cos B & = & \frac{1}{2}\left[\sin(A-B)+\sin(A+B)\right], \\[0.2cm]
\sin A\sin B & = & \frac{1}{2}\left[\cos(A-B)-\cos(A+B)\right], \\[0.2cm]
\cos A\cos B & = & \frac{1}{2}\left[\cos(A-B)+\cos(A+B)\right], \\
\end{array}
```


"""

# ╔═╡ 48a57bf3-0c09-4f43-bd1f-0e31c4acb288
md"""
**Example**

```math
\int \sin(4x)\cos(5x) dx
```
"""

# ╔═╡ 6f66f032-fcfa-43ac-978e-3598aebaa6e8
begin

	release72 = Date(2021,6,25) < now()
	solution72 = release72 ? md"[Solution](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps7.2/ps7.2-solution.pdf)" : md"Solution will be released soon"
	md"""
	### [Problem Set 7.2](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps7.2/ps7.2.pdf)
	$(solution72)
	"""
end

# ╔═╡ 1e0a2bb0-62bc-4c42-8269-7dd3943bcce1
md"""
## Section 7.3
**Trigonometric Substitution**

"""

# ╔═╡ dfa3ca61-61db-4b15-b9ba-555a0637e31c
md"""

```math
\displaystyle
\text{For }\sqrt{a^2-x^2}, \quad \text{ use } \quad x = a\sin\theta, \quad -\frac{\pi}{2}\leq \theta \leq \frac{\pi}{2}.
```
**Example** 
``\int\frac{\sqrt{9-x^2}}{x^2}dx``

------------
```math
	\displaystyle
	\text{For }\sqrt{a^2+x^2}, \quad \text{ use } \quad x = a\tan\theta, \quad -\frac{\pi}{2}< \theta <\frac{\pi}{2}.
```
**Example** ``\int\frac{dx}{x^2\sqrt{x^2+4}}``

**Example** ``\int_0^1\sqrt{1+4x^2}dx``

------------

```math
	\displaystyle
	\text{For }\sqrt{x^2-a^2}, \quad \text{ use } \quad x = a\sec\theta, \quad 0\leq \theta < \frac{\pi}{2} \text{ or }\pi \leq \theta <\frac{3\pi}{2}.
```

**Example**
``\int_0^3\sqrt{x^2-9}dx``

------------

**Example**
```math
\int \sqrt{5+4x-x^2} dx
```
"""

# ╔═╡ 0b7c21ca-a24b-4d62-8b40-beb1d7dc3281
begin
	release73 = Date(2021,6,25) < now()
	solution73 = release73 ? md"[Solution](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps7.3/ps7.3-solution.pdf)" : md"Solution will be released soon"
	md"""
	### [Problem Set 7.3](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps7.3/ps7.3.pdf)
	$(solution73)
	"""
end

# ╔═╡ b23b18fd-ebe1-481a-b606-40c4f8708e1a
md"""
## Section 7.4
**Integration of Rational Functions By Partial Fractions**

We learn how to integrate rational function: quotient of polunomial.
```math
 f(x) =\frac{P(x)}{Q(x)}, \qquad P, Q \text{ are polynomials}
```
 
**How?**

◾ __STEP 0__ : if degree of ``P`` is greater than or equal to degree of ``Q`` goto
__STEP 1__, else GOTO __STEP 2__.

◾ __STEP 1__ : Peform long division of ``P`` by ``Q`` to get 
```math
 \frac{P(x)}{Q(x)} = S(x) + \frac{R(x)}{Q(x)}
```
and apply __STEP 2__ on  ``\frac{R(x)}{Q(x)}``.

◾ __STEP 2__ : Write the __partial fractions decomposition__  

◾ __STEP 3__ : Integrate
 
"""

# ╔═╡ dcf55188-6a87-448d-809d-3c7e40817be0
md"""
### Partial Fractions Decomposition

We need to write ``\frac{R(x)}{Q(x)}`` as sum of __partial fractions__ by __factor__ ``Q(x)``. Based on the factors, we write the decomposition accoding to the following cases

__case 1__: ``Q(x)`` is a product of distinct linear factors.
we write 
```math
Q(x)=(a_1x+b_1)(a_2x+b_2)\cdots (a_kx+b_k)
```
then there exist constants ``A_1, A_2, \cdots, A_k`` such that
```math
\frac{R(x)}{Q(x)}= \frac{A_1}{a_1x+b_1}+\frac{A_2}{a_2x+b_2}+\cdots +\frac{A_k}{a_kx+b_k}
```

__case 2__: ``Q(x)`` is a product of linear factors, some of which are repeated.
say first one 
```math
Q(x)=(a_1x+b_1)^r(a_2x+b_2)\cdots (a_kx+b_k)
```
then there exist constants ``B_1, B_2, \cdots B_r, A_2, \cdots, A_k`` such that
```math
\frac{R(x)}{Q(x)}= \left[\frac{B_1}{a_1x+b_1}+\frac{B_2}{(a_1x+b_1)^2}+\cdots \frac{B_r}{(a_1x+b_1)^r}\right]+ \frac{A_2}{a_2x+b_2}+\cdots +\frac{A_k}{a_kx+b_k}
```


__case 3__: ``Q(x)`` contains irreducible quadratic factors, none of which is repeated.
say we have (Note: the quadratic factor ``ax^2+bx+c`` is irreducible if ``b^2-4ac<0``). For eaxmple if
```math
Q(x)=(ax^2+bx+c)(a_1x+b_1)
```
then there exist constants ``A, B,`` and ``C`` such that
```math
\frac{R(x)}{Q(x)}= \frac{Ax+B}{ax^2+bx+c}+\frac{C}{a_1x+b_1}
```

__case 4__: ``Q(x)`` contains irreducible quadratic factors, some of which are repeated. For example if
```math
Q(x)=(ax^2+bx+c)^r(a_1x+b_1)
```
then there exist constants ``A_1, B_1, A_2, B_2, \cdots A_r, B_r `` and ``C`` such that
```math
\frac{R(x)}{Q(x)}= \left[\frac{A_1x+B_1}{ax^2+bx+c}+\frac{A_2x+B_2}{(ax^2+bx+c)^2}+\cdots+\frac{A_rx+B_r}{(ax^2+bx+c)^r}\right]+\frac{C}{a_1x+b_1}
```



"""

# ╔═╡ 6b4a9e6c-34fc-40a8-a46f-ab9775adf6d8
md"""
**Example:** Write out the form of the partial fractions decomposition of the function
```math
\frac{x^3+x+1}{x(x-1)(x+1)^2(x^2+x+1)(x^2+4)^2}
```

"""

# ╔═╡ c2963ff4-d598-4195-a585-8884bf106b84
md"""
**More Examples**

Find
```math
\begin{array}{lll}
\text{(1)} & \int \frac{x^3+x}{x-1}dx. \\
\text{(2)} & \int \frac{x^2+2x-1}{2x^3+3x^2-2x}dx. \\
\text{(3)} & \int \frac{dx}{x^2-a^2}, \text{  where } a\not = 0 \\
\text{(4)} & \int \frac{x^4-2x^2+4x+1}{x^3-x^2-x+1}dx \\
\text{(5)} & \int \frac{2x^2-x+4}{x^3+4x}dx \\
\text{(6)} & \int \frac{4x^2-3x+2}{4x^2-4x+3}dx \\
\text{(7)} & \int \frac{1-x+2x^2-x^3}{x(x^2+1)^2}dx \\
\end{array}
```

"""

# ╔═╡ cca2812e-e1e7-499a-9c08-a76d8c77db66
md"""
**Remarks**
```math
\int \frac{dx}{x^2-a^2} = \frac{1}{2a}\ln\left|\frac{x-a}{x+a}\right|
```

```math
\int \frac{dx}{x^2+a^2} = \frac{1}{a}\tan^{-1}\left(\frac{x}{a}\right)
```
"""

# ╔═╡ 283c0dc4-d510-4581-9d26-d64e1f4bbe23
md"""
### Rationalizing Substitutions
Find
```math
\begin{array}{lll}
\text{(1)} & \int \frac{\sqrt{x+4}}{x}dx. \qquad \text{Example 9}\\
\text{(2)} & \int \frac{dx}{2\sqrt{x+3}+\;x}. \\
\end{array}
```
"""

# ╔═╡ 1e271f61-1835-49f3-9a4b-fdf7c7883c8a
md"""
### (Exercise (59 ed. 8) 63 ed. 9 )

Special Substitution (``t = \tan \left(\frac{x}{2}\right), \quad -\pi < x < \pi``)
**(for rational functions of ``\sin x`` and ``\cos x``)**
```math
\begin{array}{lll}
dx=\frac{2}{1+t^2}dt, & \cos{x}=\frac{1-t^2}{1+t^2}, &  \sin{x}=\frac{2t}{1+t^2} \\
\end{array}
```
```math
\begin{array}{lll}
\text{(1)} & \int \frac{dx}{3\sin x - 4 \cos x}. \\
\end{array}
```

"""

# ╔═╡ f8de5f89-881e-43e7-b478-9cadc4ab6950
begin
	release74 = Date(2021,6,25) < now()
	solution74 = release74 ? md"[Solution](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps7.4/ps7.4-solution.pdf)" : md"Solution will be released soon"
	md"""
	### [Problem Set 7.4](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps7.4/ps7.4.pdf)
	$(solution74)
	"""
end

# ╔═╡ 8a10bc2c-72d9-47aa-a46b-79c6cdce2d23
begin
	release75 = Date(2021,6,25) < now()
	solution75 = release75 ? md"[Solution](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps7.5/ps7.5-solution.pdf)" : md"Solution will be released soon"
md"""
## Section 7.5
**Strategy for Integration**
	
### [Problem Set 7.5](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps7.5/ps7.5.pdf)
$(solution75)
"""
end


# ╔═╡ 3d784225-debf-46db-8479-b4be15a1166a
md"""
## Section 7.8
**Improper Integrals**

*__Do you know how to evaluate the following?__*
```math

\begin{array}{llr}
\text{(1)} & \int_1^{\infty} \frac{1}{x^2} dx & (\text{Type 1}) \\ \\
\text{(2)} & \int_0^{2} \frac{1}{x-1} dx & (\text{Type 2}) \\ \\
\end{array}
```

"""

# ╔═╡ 9d55715e-f798-4d2b-876c-097397f7697b
md"""
*__Definition of an Improper Integral of Type 1__*

**(a)** If ``\int_a^t f(x) dx`` exists for every number ``t\ge a``, then
```math
\int_a^{\infty} f(x) dx = \lim_{t\to \infty} \int_a^t f(x) dx
```
provided this limit exists (as a finite number).


**(b)** If ``\int_t^b f(x) dx`` exists for every number ``t\le b``, then
```math
\int_{-\infty}^b f(x) dx = \lim_{t\to -\infty} \int_t^b f(x) dx
```
provided this limit exists (as a finite number).

The improper integrals ``\int_a^{\infty} f(x) dx`` and ``\int_{-\infty}^b f(x) dx`` are called *__convergent__* if the corresponding limit exists and *__divergent__* if the limit does not exist.

**(c)** If both ``\int_a^{\infty} f(x) dx`` and ``\int_{-\infty}^b f(x) dx`` are convergent, then we define
```math
\int_{-\infty}^{\infty} f(x) dx =  \int_{-\infty}^a f(x) dx +\int_a^{\infty} f(x) dx
```

In part (c) any real number  can be used
"""


# ╔═╡ 2b2ce933-42da-4b8b-be43-8fce0a5a1002
md"""
**Example:** Determine whether the following integrals  are convergent or divergent.

```math
\begin{array}{ll}
\text{(1)} & \int_1^{\infty} \frac{1}{x^2} dx \\ \\
\text{(2)} & \int_1^{\infty} \frac{1}{x} dx \\ \\
\text{(3)} & \int_{-\infty}^{\infty} \frac{1}{1+x^2} dx\\ \\
\end{array}
```


"""

# ╔═╡ 4b13012b-f8ac-4dce-9874-5d3f48f31878
begin
	tSlider = @bind tslider Slider(1:10000,show_value=true)
	md"""
	
	-------------
	

	t = $tSlider
	
	"""
end

# ╔═╡ 43fb92dd-f108-4bb8-afca-de94bbf28d33
begin
	pd1 = PlotData(1:0.1:10,x->1/x)
	pd2 = PlotData(1:0.1:10,x->1/x^2)
	int1 = round(integrate(1/x,(x,1,tslider)).n(),digits=3)
	int2 = round(integrate(1/x^2,(x,1,tslider)).n(),digits=3)
	pt1=tslider
	pt1=L"\int_1^{%$tslider} \frac{1}{x}dx = %$int1"
	pt2=L"\int_1^{%$tslider} \frac{1}{x^2}dx = %$int2"
	p1 = plot(pd1,annotation=[(3.5,4.5,pt1,12)],ylims=(-1,6))
	p2 = plot(pd2,annotation=[(3.5,4.5,pt2,12)],ylims=(-1,6))
	plot(p1,p2,layout=@layout([a b]))
	
end

# ╔═╡ 037d45ef-5173-43f6-b9cf-d4e4232406c8
begin
	ttSlider = @bind ttslider Slider(1:10000,show_value=true)
	pSlider = @bind pslider Slider(-10:10,show_value=true)
	md"""
	
	-------------
	
	|||
	|---|---|
	|||
	|t = $ttSlider | p = $pSlider|
	|||
	
	"""
end

# ╔═╡ 03e7485c-9c82-4d6d-ada8-1cf4e8df9b3b
begin
	tt,pp=ttslider, pslider
	fn3(p) = p>0 ? 1/x^p : p==0 ? x : x^abs(p) 
	int3(p,t) = (t<1000) ? (p==0 ? ttslider-1 : round(integrate(fn3(p),(x,1,ttslider)).n(),digits=3)) : integrate(fn3(p),(x,1,oo))
	pt3(t)= t<1000 ? L"\int_1^{%$ttslider} \frac{1}{x^{%$pslider}}dx = %$(int3(pslider,ttslider))" : L"\int_1^{\infty} \frac{1}{x^{%$pslider}}dx = %$(int3(pslider,ttslider))"
	p3=plot(1:5;annotations=[(3,4,pt3(tt),14)], showaxis=:hide,ticks=[],label=:none,
		c=:white,ylims=(0,5))
	md"""
	
	-------------
	
	$p3
	
	"""
end

# ╔═╡ 8525a617-73a2-45be-beab-f496b1c87c9b
md"""
**Remark**

```math
\int_1^{\infty} \frac{1}{x^p}dx \quad \text{ is convergent if } p > 1 \text{ and divergent if } p\leq 1.
```

"""

# ╔═╡ cd3a1142-0ebf-48e8-8438-c70d43b05070
md"""
*__Definition of an Improper Integral of Type 2__*

**(a)** If ``f`` is continuous on ``[a,b)`` and is discontinuous at ``b``, then
```math
\int_a^b f(x) dx = \lim_{t\to b^-} \int_a^t f(x) dx
```
provided this limit exists (as a finite number).


**(b)** If ``f`` is continuous on ``(a,b]`` and is discontinuous at ``a``, then
```math
\int_a^b f(x) dx = \lim_{t\to a^{+}} \int_t^b f(x) dx
```
provided this limit exists (as a finite number).

The improper integral ``\int_a^b f(x) dx`` is called **convergent** if the corresponding limit exists and **divergent** if the limit does not exist.

**(c)** If ``f`` has a discontinuity at ``c``, where ``a<c<b``, and both ``\int_a^c f(x) dx`` and ``\int_c^b f(x) dx`` are convergent, then we define
```math
\int_{a}^{b} f(x) dx =  \int_{a}^c f(x) dx +\int_c^b f(x) dx
```

"""

# ╔═╡ 1b18e34a-b862-4ed3-beb9-20a849173d18
md"""
**Example:** 
```math
\begin{array}{ll}
\text{(1)} & \int_2^5 \frac{1}{\sqrt{x-2}} dx \\ \\
\text{(2)} & \int_0^{3} \frac{1}{1-x} dx \\ \\
\text{(3)} & \int_{0}^{1} \ln x dx\\ \\
\end{array}
```


"""

# ╔═╡ d8c87a34-318b-45d4-bdb6-3629470889b7
# integrate(1/(sqrt(x-2)),(x,2,5))
# integrate(1/(x-1),(x,0,3))
# integrate(log(x),(x,0,1))

# ╔═╡ d50e295d-c390-449c-975b-70ab5296ab97
begin
	release78 = Date(2021,6,25) < now()
	solution78 = release78 ? md"[Solution](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps7.8/ps7.8-solution.pdf)" : md"Solution will be released soon"
md"""
### [Problem Set 7.8](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps7.8/ps7.8.pdf)
$(solution78)
"""
end

# ╔═╡ Cell order:
# ╟─36385992-7458-4252-902d-89153ad3e85e
# ╟─7532bb48-d0a5-11eb-0369-23288ac68dbc
# ╟─d1815ea6-9a32-4d88-b580-95f29d7ef914
# ╟─d7831013-a8bf-4bed-83f3-c436b2dd1464
# ╟─561cdfe6-fde5-4e09-bbac-8c9f9b68917c
# ╟─17b3c7a5-3170-4b6b-81b5-fc5f29eedd0f
# ╟─ea89d5dc-3d70-42d3-9cc7-6cc4c3e8ad2b
# ╟─1c821257-3b61-4187-a556-0e5736af27b2
# ╟─1a6fc415-eb31-4df1-a314-40aff9e0fa96
# ╟─030a2871-1b68-48c6-9f51-d4bcd0e86bb6
# ╟─84ad187d-e4a7-48c6-8a5c-e9e518788689
# ╟─58719d77-9812-4002-b83f-2be9050ccf8a
# ╟─5bbb85cb-a5be-4010-bd41-caa339ef92dd
# ╟─9cc8c631-741d-4020-a74c-4fb4541fce70
# ╟─c67e0db7-f34a-4e4d-852b-23d3ab18be26
# ╟─46b710e8-2903-47de-a26b-62537d8fd2e1
# ╟─48a57bf3-0c09-4f43-bd1f-0e31c4acb288
# ╟─6f66f032-fcfa-43ac-978e-3598aebaa6e8
# ╟─1e0a2bb0-62bc-4c42-8269-7dd3943bcce1
# ╟─dfa3ca61-61db-4b15-b9ba-555a0637e31c
# ╟─0b7c21ca-a24b-4d62-8b40-beb1d7dc3281
# ╟─b23b18fd-ebe1-481a-b606-40c4f8708e1a
# ╟─dcf55188-6a87-448d-809d-3c7e40817be0
# ╟─6b4a9e6c-34fc-40a8-a46f-ab9775adf6d8
# ╟─c2963ff4-d598-4195-a585-8884bf106b84
# ╟─cca2812e-e1e7-499a-9c08-a76d8c77db66
# ╟─283c0dc4-d510-4581-9d26-d64e1f4bbe23
# ╟─1e271f61-1835-49f3-9a4b-fdf7c7883c8a
# ╟─f8de5f89-881e-43e7-b478-9cadc4ab6950
# ╟─8a10bc2c-72d9-47aa-a46b-79c6cdce2d23
# ╟─3d784225-debf-46db-8479-b4be15a1166a
# ╟─9d55715e-f798-4d2b-876c-097397f7697b
# ╟─2b2ce933-42da-4b8b-be43-8fce0a5a1002
# ╟─4b13012b-f8ac-4dce-9874-5d3f48f31878
# ╟─43fb92dd-f108-4bb8-afca-de94bbf28d33
# ╟─037d45ef-5173-43f6-b9cf-d4e4232406c8
# ╟─03e7485c-9c82-4d6d-ada8-1cf4e8df9b3b
# ╟─8525a617-73a2-45be-beab-f496b1c87c9b
# ╟─cd3a1142-0ebf-48e8-8438-c70d43b05070
# ╟─1b18e34a-b862-4ed3-beb9-20a849173d18
# ╠═d8c87a34-318b-45d4-bdb6-3629470889b7
# ╟─d50e295d-c390-449c-975b-70ab5296ab97
# ╟─56c992d7-5f55-4f21-be9b-673db0c3565d
