### A Pluto.jl notebook ###
# v0.14.7

using Markdown
using InteractiveUtils

# ╔═╡ 56c992d7-5f55-4f21-be9b-673db0c3565d
begin
	using PlutoUI
	using Plots, PlotThemes, LaTeXStrings
	using SymPy
end

# ╔═╡ 36385992-7458-4252-902d-89153ad3e85e
html"""
<style>
.div-50 {
  position: relative;
  height: 50px;
}
.div-100 {
  position: relative;
  height: 100px;
}
.div-200 {
  position: relative;
  height: 200px;
}
.div-300 {
  position: relative;
  height: 300px;
}
.div-400 {
  position: relative;
  height: 400px;
}

.right-formula {
  width: 50%;
  text-align: center;
  position: absolute;
  top: 0;
  right: 0;
  padding: 5px;
  border: 2px solid blue;
}

</style>

"""

# ╔═╡ 7532bb48-d0a5-11eb-0369-23288ac68dbc
TableOfContents(title="MATH102")

# ╔═╡ d1815ea6-9a32-4d88-b580-95f29d7ef914
begin
	struct PlotData
		x::StepRangeLen
		fun::Function
		lb::Union{Integer,Vector{Float64}}
	end
	PlotData(x,f)=PlotData(x,f,0)	
	@recipe function f(t::PlotData; customcolor = :green, fillit=true)
		x, fun, lb = t.x, t.fun, t.lb
		xrotation --> 45
		zrotation --> 6, :quiet
		aspect_ratio --> 1
		framestyle --> :origin
		label-->nothing
		fill --> (fillit ? (lb,0.5,customcolor) : nothing)
		x, fun.(x)
	end
	x, y = symbols("x,y", real=true)
	html""
end

# ╔═╡ d7831013-a8bf-4bed-83f3-c436b2dd1464
md"""
# Chapter 7: Techniques of Integration

## Section 7.1
**Integration by Parts**

*The integration rule that corresponds to the Product Rule for differentiation is called __integration by parts__*
"""

# ╔═╡ 561cdfe6-fde5-4e09-bbac-8c9f9b68917c
md"""
### Indefinite Integrals
```math
\int f(x)g'\,(x) dx = f(x) g(x) - \int g(x) f'\,(x) dx
```
"""

# ╔═╡ 17b3c7a5-3170-4b6b-81b5-fc5f29eedd0f
md"""
**Example**

```math 
\int x \cos(x) dx 
```


"""

# ╔═╡ ea89d5dc-3d70-42d3-9cc7-6cc4c3e8ad2b
begin
	
	md"""
	**Solution:**
	
	```math
	\int x \cos(x) dx = \int \underbrace{x}_{f(x)} \overbrace{\cos(x)}^{g'(x)} dx = x \sin(x) - \int \sin(x) \overbrace{ \;\;\;\;dx}^{f'\,(x) dx} = x\sin(x) + \cos(x) +C  
	
	```
	"""
end

# ╔═╡ 1c821257-3b61-4187-a556-0e5736af27b2
md"""
**Remarks:**

```math
\int f(x)g'\,(x) dx = f(x) g(x) - \int g(x) f'\,(x) dx 
```
  
```math
\begin{array}{lll}
  u=f(x), & \qquad & dv=g'(x) dx \\
      &\searrow&\\
  du = f'(x)dx & \underset{-}{\longleftarrow} & v = g(x) 
  \end{array}
```


  
```math
\int u dv = uv - \int v du 
```
**_It is helpful to use the pattern:_**
```math
\begin{array}{rcr}
  u=\fbox{\rule{0.2in}{0pt}\rule[-0.1ex]{0pt}{2ex}} & \qquad & dv=\fbox{\rule{0.2in}{0pt}\rule[-0.1ex]{0pt}{2ex}} \\
      &\searrow&\\
  du = \fbox{\rule{0.2in}{0pt}\rule[-0.1ex]{0pt}{2ex}}& \underset{-}{\longleftarrow} & v = \fbox{\rule{0.2in}{0pt}\rule[-0.1ex]{0pt}{2ex}} 
  \end{array}
```

### Definite Integrals

```math
\int_a^b u dv = \left[uv\right]_a^b - \int_a^b v du
```
"""

# ╔═╡ 1a6fc415-eb31-4df1-a314-40aff9e0fa96
md"""
### Examples
__SOLUTION IN CLASS__

1. ``\int \ln x dx``
2. ``\int t^2 e^t dt ``
3. ``\int e^x \sin(x)dx``
4. ``\int_0^1 \tan^{-1}x dx``
5. ``\int x^3 \sin{\left(x\over 6\right)} dx``
6. ``\int \sin^5(x) dx``

"""

# ╔═╡ 030a2871-1b68-48c6-9f51-d4bcd0e86bb6
md"""
**Example**

Calculate the volume generated by rotating the region bounded by the curves ``y=\ln x``, ``y=0``, and ``x=2`` about each axis.
"""

# ╔═╡ 84ad187d-e4a7-48c6-8a5c-e9e518788689
md"""
### [Problem Set 7.1](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps7.1/ps7.1.pdf)

"""

# ╔═╡ 58719d77-9812-4002-b83f-2be9050ccf8a
md"""
## Section 7.2
**Trigonometric Integrals**

**RECALL**

```math



\displaystyle
\sin^2 x + \cos^2 x =1, \quad  \tan^2 x + 1 =\sec^2 x,  \quad  1+\cot^2 x  =\csc^2 x,

```

```math
\displaystyle
\cos^2 x = \frac{1 +\cos 2x }{2}, \quad \sin^2 x = \frac{1 -\cos 2x }{2}
```

```math
\displaystyle
\begin{array}{ccc}
\sin A\cos B & = & \frac{1}{2}\left[\sin(A-B)+\sin(A+B)\right], \\[0.2cm]
\sin A\sin B & = & \frac{1}{2}\left[\cos(A-B)-\cos(A+B)\right], \\[0.2cm]
\cos A\cos B & = & \frac{1}{2}\left[\cos(A-B)+\cos(A+B)\right], \\
\end{array}
```

```math
\int \tan x dx = \ln|\sec x| +C, \quad \int \sec x dx = \ln|\sec x+\tan x| +C
```


```math
\int \cot x dx = -\ln|\csc x| +C, \quad \int \csc x dx = \ln|\csc x-\cot x| +C
```
"""

# ╔═╡ 5bbb85cb-a5be-4010-bd41-caa339ef92dd
md"""
### Integrals of Powers of Sine and Cosine
```math
\int \sin^mx \cos^n x dx
```

* ``m`` is ``{\color{red}\text{odd}}``, write as ``\int \sin^{m-1}x \cos^n x \sin x  dx``. _Example_: $\int \sin^5x \cos^2 x dx$


* ``n`` is ``{\color{red}\text{odd}}``,  write as ``\int \sin^mx \cos^{n-1}\cos x  dx``. _Example_ ``\int \sin^5x \cos^3 x dx``


* ``m`` and ``n`` are ``{\color{red}\text{even}}``, use formulae (_Example_ ``\int \cos^2 x dx`` and  ``\int \sin^4 x dx``)
```math
\sin^2(x)=\frac{1-\cos(2x)}{2}, \quad \cos^2(x)=\frac{1+\cos(2x)}{2}.
```
"""

# ╔═╡ 9cc8c631-741d-4020-a74c-4fb4541fce70
md"""
### Integrals of Powers of Secant and Tangent

```math
\int \tan^mx \sec^n x dx
```

* ``n`` is even, write as ``\int \tan^mx \sec^{n-2}\sec^2 x  dx``. _Example_ ``\int \tan^6x \sec^4 x dx``


* ``m`` is odd, write as ``\int \tan^{m-1}x \sec^{n-1}\tan x\sec x  dx``. _Example_ ``\int \tan^5x \sec^7 x dx``.


"""

# ╔═╡ c67e0db7-f34a-4e4d-852b-23d3ab18be26
md"""
**Examples**

1. ``\int \tan^3 x dx``


2. ``\int \sec^3 x dx``

"""

# ╔═╡ 46b710e8-2903-47de-a26b-62537d8fd2e1
md"""
### Using Product Identities
```math 
\int \sin mx \cos n x dx, 
```
```math
\int \sin mx \sin n x dx, 
```
```math
\int \cos mx \cos n x dx.
```

Use


```math
\displaystyle
\begin{array}{ccc}
\sin A\cos B & = & \frac{1}{2}\left[\sin(A-B)+\sin(A+B)\right], \\[0.2cm]
\sin A\sin B & = & \frac{1}{2}\left[\cos(A-B)-\cos(A+B)\right], \\[0.2cm]
\cos A\cos B & = & \frac{1}{2}\left[\cos(A-B)+\cos(A+B)\right], \\
\end{array}
```


"""

# ╔═╡ 48a57bf3-0c09-4f43-bd1f-0e31c4acb288
md"""
**Example**

```math
\int \sin(4x)\cos(5x) dx
```
"""

# ╔═╡ 6f66f032-fcfa-43ac-978e-3598aebaa6e8
md"""
### [Problem Set 7.2](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps7.2/ps7.2.pdf)

"""

# ╔═╡ 1e0a2bb0-62bc-4c42-8269-7dd3943bcce1
md"""
## Section 7.3
**Trigonometric Substitution**

"""

# ╔═╡ dfa3ca61-61db-4b15-b9ba-555a0637e31c
md"""

```math
\displaystyle
\text{For }\sqrt{a^2-x^2}, \quad \text{ use } \quad x = a\sin\theta, \quad 0\leq \theta \leq \pi.
```
**Example** 
``\int\frac{\sqrt{9-x^2}}{x^2}dx``

------------
```math
	\displaystyle
	\text{For }\sqrt{a^2+x^2}, \quad \text{ use } \quad x = a\tan\theta, \quad -\frac{\pi}{2}< \theta <\frac{\pi}{2}.
```
**Example** ``\int\frac{dx}{x^2\sqrt{x^2+4}}``

------------

```math
	\displaystyle
	\text{For }\sqrt{x^2-a^2}, \quad \text{ use } \quad x = a\sec\theta, \quad 0\leq \theta < \frac{\pi}{2} \text{ or }\pi \leq \theta <\frac{3\pi}{2}.
```

**Example**
``\int_0^3\sqrt{9-x^2}dx``

------------

**Example**
```math
\int \sqrt{5+4x-x^2} dx
```
"""

# ╔═╡ 0b7c21ca-a24b-4d62-8b40-beb1d7dc3281
md"""
### [Problem Set 7.3](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps7.3/ps7.3.pdf)

"""

# ╔═╡ Cell order:
# ╟─36385992-7458-4252-902d-89153ad3e85e
# ╟─7532bb48-d0a5-11eb-0369-23288ac68dbc
# ╟─d1815ea6-9a32-4d88-b580-95f29d7ef914
# ╟─d7831013-a8bf-4bed-83f3-c436b2dd1464
# ╟─561cdfe6-fde5-4e09-bbac-8c9f9b68917c
# ╟─17b3c7a5-3170-4b6b-81b5-fc5f29eedd0f
# ╟─ea89d5dc-3d70-42d3-9cc7-6cc4c3e8ad2b
# ╟─1c821257-3b61-4187-a556-0e5736af27b2
# ╟─1a6fc415-eb31-4df1-a314-40aff9e0fa96
# ╟─030a2871-1b68-48c6-9f51-d4bcd0e86bb6
# ╟─84ad187d-e4a7-48c6-8a5c-e9e518788689
# ╟─58719d77-9812-4002-b83f-2be9050ccf8a
# ╟─5bbb85cb-a5be-4010-bd41-caa339ef92dd
# ╟─9cc8c631-741d-4020-a74c-4fb4541fce70
# ╟─c67e0db7-f34a-4e4d-852b-23d3ab18be26
# ╟─46b710e8-2903-47de-a26b-62537d8fd2e1
# ╟─48a57bf3-0c09-4f43-bd1f-0e31c4acb288
# ╟─6f66f032-fcfa-43ac-978e-3598aebaa6e8
# ╟─1e0a2bb0-62bc-4c42-8269-7dd3943bcce1
# ╟─dfa3ca61-61db-4b15-b9ba-555a0637e31c
# ╟─0b7c21ca-a24b-4d62-8b40-beb1d7dc3281
# ╟─56c992d7-5f55-4f21-be9b-673db0c3565d
