### A Pluto.jl notebook ###
# v0.14.7

using Markdown
using InteractiveUtils

# ╔═╡ 01820aa0-d887-11eb-0307-758b12f13e10
begin
	using PlutoUI
	using Plots, PlotThemes, LaTeXStrings
	using SymPy
	using Dates
	using ImageShow, ImageIO, ImageTransformations
	using FileIO
	using HypertextLiteral
end

# ╔═╡ a267a6be-6141-4472-bc34-156ba6bf8f56
TableOfContents(title="MATH 102")

# ╔═╡ e1426763-9558-4e05-a10f-3713badece23
x = symbols("x", real=true);html""

# ╔═╡ 9444b967-d4d9-441a-b295-0cc29c7fb578
begin
	p1 = plot(x->exp(-x)*cos(x),showaxis=false, ticks=nothing,label=nothing)
	md"""
	# Chapter 8: Further Applications of Integration

	## Section 8.1
	**Arc Length**

	**_QUESTION_**

	What is the length of the curve?

	$p1
	"""
end

# ╔═╡ a8d3d297-bd27-408b-857f-95ae790530a3
begin 
	img1 = load("./imgs/8.1/img1.png")
	imresize(img1,(400,900))
end

# ╔═╡ 1339001c-ad6a-485f-b2b9-43f8011c4d6b
md"""
### The Arc Length Formula
If ``f'`` is continuous on ``[a,b]``, then the length of the curve ``y=f(x)``, ``a\leq x\leq b``, is 
```math
L=\int_a^b \sqrt{1+\left[f'(x)\right]^2} dx
```

**Remarks**
- Using Leibniz notation 
```math
L=\int_a^b \sqrt{1+\left(\frac{dy}{dx}\right)^2} dx
```

**Example 1:** Find the length of the arc of the semicubical parabola $y^2=x^3$ between the points $(1,1)$ and $(4,8)$. 
"""

# ╔═╡ cf63184e-1d0e-4917-bd0d-ee965abc1eb9
md"""
**Remark :**

- If ``x=g(y)``, ``c\leq y\leq d`` and ``g'(y)`` is continuous, then we have 
```math
L = \int_c^d \sqrt{1+\left[g'(y)\right]^2} dy=\int_c^d \sqrt{1+\left(\frac{dx}{dy}\right)^2} dy
```

**Example 2:**
Find the length of the arc of the parabola $y^2=x$ between the
points $(0,0)$ and $(1,1)$.
"""

# ╔═╡ 5fd0f18f-d40a-4492-a63d-566037c42ae9
md"""
**Example 3:** __Set up an integral__ for the length of the arc of the hyperbola $xy=1$ from the point $(1,1)$ to the point $(2,{1 \over 2})$ 

"""

# ╔═╡ da787418-b9b7-437d-8d56-9a201936b9e7
integrate(sqrt(1 + 1/x^4),(x,1,2)).n()

# ╔═╡ fe1e7aae-e0f1-47db-a129-4d35b1b27938
md"""
### The Arc Length Function
```math
s(x) = \int_a^x\sqrt{1+\left[f'(t)\right]^2} dt
```

**The differential of arc length is**

```math 
ds = \sqrt{1+\left(\frac{dy}{dx}\right)^2} dx
```
"""

# ╔═╡ 7f026b61-84b8-466b-a270-491ba0fbcaf9
begin
	img2 = load("./imgs/8.1/img2.png")
	imresize(img2,(300,500))
end

# ╔═╡ d822d7aa-d77e-4cea-a3ef-40a72b72ccf4
md"""
**Example 4:** Find the arc length function for the curve $y=x^2-{1 \over 8}\ln x$ taking $P_0(1,1)$ as the starting point.
"""

# ╔═╡ bf7bb4e5-abae-4051-97ad-6d08e83871d6
md"""
## Section 2:
**Surface Area of Solid of revolution**



"""


# ╔═╡ 1594d4fe-f421-4d37-8a84-1135b4486a8e
begin 
	img3 = load("./imgs/8.2/img1.png")
	imresize(img3,(500,550))
end

# ╔═╡ b84fd528-21c2-4161-aab1-2ab41f58cb98
md"""
In the case where ``f`` is positive and has a continuous derivative, we define the **_surface area_** of the surface obtained by rotating the curve ``y=f(x)``, ``a\leq x\leq b``, about the ``x``-axis as

```math
S = \int_a^b 2\pi f(x) \sqrt{1+\left[f'(x)\right]^2} dx
=\int_a^b 2\pi y \sqrt{1+\left(\frac{dy}{dx}\right)^2} dx
```

If the curve is described as ``x=g(x)``, ``c\leq y\leq d``, then the formula for **_surface area_** becomes

```math
S =
\int_c^d 2\pi y \sqrt{1+\left(\frac{dx}{dy}\right)^2} dy
```

**Remarkd**
* Symbolically
```math
S=\int 2\pi y ds
```

```math
S=\int 2\pi x ds
```
"""

# ╔═╡ aa5e90e5-26f4-436e-acdb-6be4c557e568
md"""
**Example :**
The curve ``y=\sqrt{4-x^2}``, ``-1\leq x \leq 1``, is an arc of the circle ``x^2+y^2=4``. Find the area of the surface obtained by rotating this arc about the ``x``-axis.

**Example :**
The arc of the parabola ``y=x^2`` from ``(1,1)`` to ``(2,4)`` is rotated about the ``y``-axis. Find the area of the resulting surface

**Example :**
Find the area of the surface generated by rotating the curve ``y=e^x`` ,
``0\leq x\leq 1``, about the ``x``-axis.

"""



# ╔═╡ 63c5c52a-0efd-4532-9043-44f9c092920f
md"""
### [Problem Set 8.1-8.2](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps8.1/ps8.1.pdf)

[Solution](https://github.com/mmogib/math102-term203/blob/master/problem_sets/ps/ps8.1/ps8.1-solution.pdf)
"""

# ╔═╡ Cell order:
# ╟─a267a6be-6141-4472-bc34-156ba6bf8f56
# ╟─e1426763-9558-4e05-a10f-3713badece23
# ╟─9444b967-d4d9-441a-b295-0cc29c7fb578
# ╟─a8d3d297-bd27-408b-857f-95ae790530a3
# ╟─1339001c-ad6a-485f-b2b9-43f8011c4d6b
# ╟─cf63184e-1d0e-4917-bd0d-ee965abc1eb9
# ╟─5fd0f18f-d40a-4492-a63d-566037c42ae9
# ╟─da787418-b9b7-437d-8d56-9a201936b9e7
# ╟─fe1e7aae-e0f1-47db-a129-4d35b1b27938
# ╟─7f026b61-84b8-466b-a270-491ba0fbcaf9
# ╟─d822d7aa-d77e-4cea-a3ef-40a72b72ccf4
# ╟─bf7bb4e5-abae-4051-97ad-6d08e83871d6
# ╟─1594d4fe-f421-4d37-8a84-1135b4486a8e
# ╟─b84fd528-21c2-4161-aab1-2ab41f58cb98
# ╟─aa5e90e5-26f4-436e-acdb-6be4c557e568
# ╠═63c5c52a-0efd-4532-9043-44f9c092920f
# ╠═01820aa0-d887-11eb-0307-758b12f13e10
