# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [10.x, 12.x, 14.x, 15.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Check out master
    - uses: actions/checkout@v2
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.6.0
    - name: Franklin
      run: julia -e '
        using Pkg;
        Pkg.add([
        Pkg.PackageSpec(name="NodeJS", version="1.1.1"),
        Pkg.PackageSpec(name="JSON", version="0.21.1"),
        ]);
        using NodeJS;
        
        "== Run Coping ==";
        "== Place rendered notebooks in the website folder ==";
        cp("./chapters/imgs", "./frontend");'
